### ISSUE TITLE
IE 11 issue - "Access Denied" in getOwnPropertyNames

### ISSUE THREAD

**Issue by gursharan001** [aurelia/polyfills#22]
Reference fix in knockout - https://github.com/SteveSanderson/knockout-es5/pull/43

Reproduced using minimal ES2016 getting started kit (and upgrading everything to latest version). To reproduce, add an iframe which refers to any other domain e.g., adding below to index.html produces error in IE11
`<iframe src="https://xkcd.com"></iframe>`

Attached a minimal project to reproduce.
[polyfill-error.zip](https://github.com/aurelia/polyfills/files/209390/polyfill-error.zip)

**Comment by EisenbergEffect** [comment]
I think we've got a fix coming. See this PR: https://github.com/aurelia/polyfills/pull/21 Give it a try and let me know if it fixes your issues.

**Comment by gursharan001** [comment]
PR fixes the issue in aurelia polyfill with the repro code.

However, in my application the same error is now raised in Babel browser.js file (5.8.38). I don't have a repro for it at this point so I am not sure what is going wrong.

**Comment by gursharan001** [comment]
I managed to reproduce this error which is not fixed by PR: #21 Attaching the repro code.

[polyfill-error-2iframes.zip](https://github.com/aurelia/polyfills/files/210979/polyfill-error-2iframes.zip)

**Comment by EisenbergEffect** [comment]
Is it an error in our polyfills or in babel's browser.js?

**Comment by gursharan001** [comment]
The error is in babel's browser.js.

**Comment by SassonHW** [comment]
i having the same issue (IE 11 issue - "Access Denied" in getOwnPropertyNames) in my app using aurelia-polyfills@1.0.0-beta.1.1.3


![pasted image at 2016_05_08 05_33 pm](https://cloud.githubusercontent.com/assets/18256326/15098391/07060ccc-1545-11e6-877b-bdbbfca6feaa.png)
 ???

**Comment by EisenbergEffect** [comment]
This should be fixed now.

**Comment by dtaalbers** [comment]
Hi,

I am currently working on an Aurelia CLI app (version 0.20.2) with aurelia-polyfills (1.1.1) but still encountering this issue. Any idea what I can do to resolve this problem?

<img width="981" alt="screen shot 2016-10-14 at 16 20 16" src="https://cloud.githubusercontent.com/assets/6512556/19390818/1e782086-922a-11e6-94b9-a8daf756b3e8.png">

<img width="1440" alt="screen shot 2016-10-14 at 16 18 15" src="https://cloud.githubusercontent.com/assets/6512556/19390814/149e0774-922a-11e6-8be8-a943d9719eab.png">

**Comment by iovergard** [comment]
I am also still seeing this issue with the latest version of aurelia-polyfills

**Comment by mikeesouth** [comment]
Me too - any fix or workaround available?

**Comment by mikeesouth** [comment]
I've been investigating this issue more. It does not occur on Chrome, Firefox and Edge (all latest versions) but it occurs 100% of the time on IE11. Just as @dtaalbers I am using Auth0 that opens a new window a brief moment for authentication.

@dtaalbers have you found any workaround that works with the auth0 authentication flow?
@EisenbergEffect should we raise a new issue or can this be re-opened?

**Comment by EisenbergEffect** [comment]
Please raise a new page and provide a repro. Thanks!

**Comment by kobyriskovich** [comment]
Any update on how to fix this?

**Comment by genachka** [comment]
+1
Same as @mikeesouth we're not seeing this in current releases of Chrome or Firefox. Only on IE 11 (we're using 11.0.9600.18617) 100% of the time as well.

**Comment by nabilusmani** [comment]
Is there a solution available for this? I just installed the recent aurelia cli 4.1.2 and polyfills 1.2.1, but am still running into this issue on IE 11.

**Comment by magnusdanielson** [comment]
In aurelia-polyfills.js i changed the definition of
`descriptor.value = function getOwnPropertyNames(o)`

to the following:
`descriptor.value = function getOwnPropertyNames(o) {
    var cachedWindowNames = typeof window === 'object' ? Object.getOwnPropertyNames(window) : [];
    var originalObjectGetOwnPropertyNames = Object.getOwnPropertyNames;
    if (_toString(o) === '[object Window]') {
          try {
            return originalObjectGetOwnPropertyNames(o);
          } catch (e) {
            // IE bug where layout engine calls userland gOPN for cross-domain `window` objects
            return [].concat([], cachedWindowNames);
          }
        }

    return gOPN(o).filter(onlyNonSymbols);
  };`

When using IE 11 and opening the developer toolbar and having an IFrame inserted anywhere in your document you will get in trouble because IE tries to call getOwnPropertyNames but that is not allowed if the IFrame domain is different from the document domain. I am really not an expert on this, most credit goes to https://github.com/ljharb

**Comment by gursharan001** [comment]
That's f****ing awesome!!! Is there a PR to try?

**Comment by EisenbergEffect** [comment]
@magnusdanielson Would you be interested in submitting a PR?

**Comment by magnusdanielson** [comment]
Sure, I will give it a try. 
I'll ping you when done.

**Comment by JeroenDragt** [comment]
@magnusdanielson Any news on the PR?

**Comment by ErikSchierboom** [comment]
I'm also having this issue! Any update @magnusdanielson?
